[package]
name = "arvelie"
version = "0.1.0"
authors = ["Genevive Alfirevic <gen@nyble.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confindent = "2.0"
dirs = "3.0"
time = "0.2"
